/**
 * @file acmp_config.c
 * @date 2016-02-04
 *
 * NOTE:
 * This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * ACMP_CONFIG v4.1.2 - Configures the properties of analog comparator peripheral instance.
 *
 * Copyright (c) 2016, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG (dave@infineon.com).
 ***********************************************************************************************************************
 *
 * Change History
 * --------------
 *
 * 2015-05-13:
 *     - Initial version<br>
 *
 * 2015-06-04:
 *     - ACMP_CONFIG_Init() API updated for XMC_ACMP_Init() API calls return value check removal.<br>
 *
 * 2016-02-04:
 *     - Code size optimization done on configuration structure.<br>
 *     - Function pointer based instance specific initialization implemented.ACMP_CONFIG_Init() API updated.<br>
 *     - Updated for public release(Productive Version)
 *
 * @endcond
 *
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "acmp_config.h"

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * LOCAL DATA
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * LOCAL ROUTINES
 **********************************************************************************************************************/

 /**********************************************************************************************************************
 * API IMPLEMENTATION
 **********************************************************************************************************************/

/* Returns the version of the ACMP_CONFIG APP. */
DAVE_APP_VERSION_t ACMP_CONFIG_GetAppVersion(void)
{
  DAVE_APP_VERSION_t version;

  version.major = ACMP_CONFIG_MAJOR_VERSION;
  version.minor = ACMP_CONFIG_MINOR_VERSION;
  version.patch = ACMP_CONFIG_PATCH_VERSION;

  return version;
}


/* Initializes the analog comparator instance with the generated configuration */
ACMP_CONFIG_STATUS_t ACMP_CONFIG_Init(const ACMP_CONFIG_t *const handle)
{
  ACMP_CONFIG_STATUS_t status;

  XMC_ASSERT("ACMP_CONFIG_Init APP handle function pointer uninitialized", (((handle != NULL) &&
      (handle->config != NULL)) && ((handle->config->acmp_config_init_func != NULL))))

  /* Initialize the GLOBAL_ACMP APP with associated handle parameter*/
  status = (ACMP_CONFIG_STATUS_t)GLOBAL_ACMP_Init(handle->global_handle);

  if ( status != ACMP_CONFIG_STATUS_SUCCESS )
  {
    status = ACMP_CONFIG_STATUS_FAILURE;
  }
  else
  {
    /* Initialize the ACMP instance using the function defined in ACMP_CONFIG_Conf file*/
    handle->acmp_config_init_func();

    status = ACMP_CONFIG_STATUS_SUCCESS;
  }

  return (status);
}

